package com.maths.challenge.component;

import com.maths.challenge.generated.model.AnswerResponse;
import com.maths.challenge.generated.model.QuestionRequest;
import com.maths.challenge.service.QuestionHandler;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.util.regex.Pattern;

/**
 * Resolves the appropriate {@link QuestionHandler} based on the type of question received.
 * It determines whether a question is an arithmetic expression or a basic question and delegates
 * the handling to the respective handler.
 */
@Slf4j
@Component
public class QuestionHandlerResolver {

    /**
     * Regular expression pattern to identify arithmetic expressions.
     */
    private static final Pattern ARITHMETIC_PATTERN = Pattern.compile("^[0-9+\\-*/.\\s()]+$");

    /**
     * Handler for basic questions.
     */
    private final QuestionHandler basicQuestionHandler;
    /**
     * Handler for arithmetic questions.
     */
    private final QuestionHandler arithmeticQuestionHandler;

    /**
     * Constructs a new QuestionHandlerResolver with the specified question handlers.
     *
     * @param basicQuestionHandler      The handler for basic questions.
     * @param arithmeticQuestionHandler The handler for arithmetic questions.
     */
    public QuestionHandlerResolver(@Qualifier("BasicQuestionService") QuestionHandler basicQuestionHandler,
                                   @Qualifier("ArithmeticService") QuestionHandler arithmeticQuestionHandler) {
        this.basicQuestionHandler = basicQuestionHandler;
        this.arithmeticQuestionHandler = arithmeticQuestionHandler;
    }

    /**
     * Handles the given question request by delegating it to the appropriate question handler.
     *
     * @param questionRequest The question request to handle.
     * @return The answer response generated by the handler.
     */
    public AnswerResponse handle(QuestionRequest questionRequest) {
        if (isArithmeticQuestion(questionRequest.getQuestion())) {
            log.info("It is an arithmetic question : {}", questionRequest.getQuestion());
            return this.arithmeticQuestionHandler.handleQuestion(questionRequest);
        }
        log.info("It is a basic question : {}", questionRequest.getQuestion());
        return this.basicQuestionHandler.handleQuestion(questionRequest);
    }

    /**
     * Checks if the given question is an arithmetic expression.
     *
     * @param question The question string to check.
     * @return true if the question is an arithmetic expression, false otherwise.
     */
    private boolean isArithmeticQuestion(String question) {
        return ARITHMETIC_PATTERN.matcher(question).matches();
    }
}
